### ISSUE TITLE
Moving from Unity to Mate produces this error

### ISSUE THREAD

**Issue by orschiro** [orschiro/dslli#2]
Dear @probonopd,

Do you have any idea why moving from Ubuntu 17.04 Unity to Mate might cause this failure when trying to run the indicator?

```
orschiro@x230:~$ Software/dslli/dslli-indicator.AppImage 
/bin/bash: ../lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by /bin/bash)
```

**Comment by probonopd** [comment]
That should be purely cosmetic and can be ignored, as far as I know.

**Comment by orschiro** [comment]
Thank you very much for your prompt feedback!

First, I thought this warning prevented the tray icon from showing on Mate. 

However, I had to enable Indicators in Mate Tweak for the indicator to show. :-)
